### ISSUE TITLE
MSVC toolset selection?

### ISSUE THREAD

**Issue by hlnkn** [ChaseSunstrom/cforge#2]
Hi,

cforge sounds really interesting and I'm going to port a project of mine to it. Is it possible to specify MSVC toolsets? If for example I'm using v141_xp, is there a way to tell cforge to use that?

Thank you

**Comment by ChaseSunstrom** [comment]
Yes, you can specify MSVC toolsets in cforge. The build system supports toolset specification through the CMake options when configuring Visual Studio builds.

Based on your codebase, there are two main ways to specify MSVC toolsets such as v141_xp:

## 1. Using build.cmake_options in your cforge.toml

You can add the toolset specification to the global CMake options:

```toml
[build]
cmake_options = ["-T", "v141_xp"]
```
## 2. Per-configuration toolset specification
If you want to use different toolsets for different build configurations, you can specify them in the configs section:

```toml
[build.configs.Debug]
cmake_options = ["-T", "v141_xp"]

[build.configs.Release]
cmake_options = ["-T", "v141_xp"]
```
