### ISSUE TITLE
Default config is set to "Release" but its not compiling in Release mode?

### ISSUE THREAD

**Issue by lamweilun** [ChaseSunstrom/cforge#3]
Setup:
- Windows 11
- VSCode
- clang-cl
- cforge v1.2.2

main.cpp
```C++
#include <iostream>

#ifdef NDEBUG
#define str "Release"
#else
#define str "Debug"
#endif

int main(int argc, char *argv[]) {
    std::cout << str << std::endl;
    return 0;
}
```

cforge.toml
```TOML
[project]
name = "test"
version = "0.1.0"
description = "A C/C++ project built with cforge"
type = "executable"
language = "c++"
standard = "c++17"

[build]
build_dir = "build"
generator = "default"
default_config = "Release"
debug = true
compiler = "clang-cl"

[build.configs.Release]
defines = ["NDEBUG"]
flags = ["OPTIMIZE"]

[build.configs.Debug]
defines = ["DEBUG"]
flags = ["DEBUG_INFO", "NO_OPT"]

[targets.default]
sources = ["src/**.cpp", "src/**.c"]
include_dirs = ["include"]

[output]
bin_dir = "bin"
lib_dir = "lib"
obj_dir = "obj"
```

Description:
- I ran `cforge init` in a folder and I have a main.cpp that basically prints "Release" if NDEBUG is defined, else it would print "Debug". NDEBUG is defined under build.configs.Release, DEBUG is defined under build.configs.Debug. The default_config is set to "Release". I ran `cforge build` and then ran `cforge run`, and it printed "Debug". I tried commenting "debug = true" and I ran `cforge clean` then `cforge build` then `cforge run` again. And it still printed "Debug" instead of "Release".
